services:
  db:
    image: postgres:16
    container_name: tekknowledge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tekknowledge
    ports:
      - "5432:5432"
    volumes:
      - tekknowledge_pgdata:/var/lib/postgresql/data

volumes:
  tekknowledge_pgdata:
